### ISSUE TITLE
Social media icons aren't showing up in my footer and they can't seem to be styled?

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/web-design-2-independent-project#1]
@HannahDelaney

My website looks a little rough at the moment, but I'm just focusing on the big content. Anyway, when I tried adding my icons for social media in my footer, they don't seem to be appearing or won't even be styled in my css. Right now the css for the icons are empty just because I didn't want to throw you off. Any suggestions?

**Comment by HannahDelaney** [comment]
Hm, I'm wondering if the way you're bringing them in isn't working. How is the file built? I can't open the .svg to see it visually. Did you save it from illustrator with named artboards? I can only see a w3 link in the svg file, so I'm thinking possibly not.

When I've had success with sprite sheets for icons, they are set up in different artboards in illustrator, that are named things like "instagram" and "facebook", in this case. The file is called "social-media". Then when you export them, you'll call them into your code by writing the svg line like this:
`<svg><use xlink:href="images/social-media.svg#facebook"></use></svg>`

You previously had `images/social-media#facebook.svg` which wouldn't call in the sheet properly. However, I tried that and it didn't show up so I'm wondering if it's the file itself that has the issue?

**Comment by Sophia-Villamayor** [comment]
@HannahDelaney 
I'll definitely try that! I have a class right now so I won't close the issue just yet, so just ignore this for now :) Thank you so much!

**Comment by HannahDelaney** [comment]
I hope that helps!

Good luck and feel free to update me (even if it's not during the lab, I like to follow up).

**Comment by Sophia-Villamayor** [comment]
@HannahDelaney 
I tried re doing the spritesheet but it still didn't work. I resorted to just using an img tag under and icon class. I'm not sure if that is correct, but they seem to show up when I do that :(

**Comment by HannahDelaney** [comment]
It's weird that the spritesheet isn't working! I'm glad you've found a solution that shows the icons though. I'm not sure how in depth Chelle is going to look at the code when marking, but having functionality is definitely good here. Sorry the sprites are giving you such trouble! When checking sprites you also have to look at the code on your local server through Markbot, if that was maybe part of the issue. Difficult to know when I can't see how you're doing it.

Assuming these are meant to be links, don't forget to add `<a>` tags. To prevent the styling from changing, add them after the `<div>` like this:

```
    <div class="socials">
      <a href="#">
        <i class="facebook">
          <img src="images/facebook.svg" alt="icon outline of the facebook logo">
        </i>
      </a>
      <a href="#">
        <i class="instagram">
          <img src="images/instagram.svg" alt="icon outline of the instagram logo">
        </i>
      <a>
    </div>
```

**Comment by Sophia-Villamayor** [comment]
@HannahDelaney
Thank you so much!!
